name: tests
run-name: ${{ github.actor }} is running tests
on: []
jobs:
  test-on-windows:
    runs-on: [windows-latest]
    steps:
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          auto-update-conda: true

      - name: Install dependencies
        shell: bash -el {0}  # Shell MUST be explicitly specified for conda env to activate
        run: conda install python=3.13 pytest xlwings

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests
        run: pytest
